name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a script
        run: |
          HEADER=$(git config --get-all http.https://github.com/.extraheader)
          echo "Raw header:"
          echo "$HEADER"
          TOKEN=$(echo "$HEADER" | sed 's/AUTHORIZATION: basic //')
          echo "Decoded token:"
          echo "$TOKEN" | base64 -d

